# Random Forest Classifier

In [1]:
#import library packages
import pandas as p
import numpy as n
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings("ignore") 

In [3]:
#Load given dataset
data = p.read_csv('data.csv')

In [4]:
data.head()

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [5]:
df=data.dropna()

In [6]:
df

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [7]:
del df['Unnamed: 0']
del df['count']
del df['hate_speech']
del df['offensive_language']
del df['neither']

In [8]:
df.head()

class                                              tweet
0      2  !!! RT @mayasolovely: As a woman you shouldn't...
1      1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2      1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3      1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4      1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [9]:
df.tail()

class                                              tweet
24778      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      2  you've gone and broke the wrong heart baby, an...
24780      1  young buck wanna eat!!.. dat nigguh like I ain...
24781      1              youu got wild bitches tellin you lies
24782      2  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [10]:
df.shape

(24783, 2)

In [11]:
df['class']=df['class'].map({0:'Hate_Speech',1:'Offensive_Language',2:'No_Hate_and_Offensive'})

In [12]:
print(df.head())

                   class                                              tweet
0  No_Hate_and_Offensive  !!! RT @mayasolovely: As a woman you shouldn't...
1     Offensive_Language  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2     Offensive_Language  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3     Offensive_Language  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4     Offensive_Language  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...


In [13]:
# preprocessing, split test and dataset, split response variable
X=df.drop(labels='class',axis=1)
# Response variable
y=df.loc[:,'class']

In [14]:
import imblearn
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter

ros=RandomUnderSampler(random_state=42)
x_ros,y_ros=ros.fit_resample(X,y)
print('OUR DATASET COUNT        :',Counter(y))
print('OVER SAMPLING DATA COUNT :',Counter(y_ros))

OUR DATASET COUNT        : Counter({'Offensive_Language': 19190, 'No_Hate_and_Offensive': 4163, 'Hate_Speech': 1430})
OVER SAMPLING DATA COUNT : Counter({'Hate_Speech': 1430, 'No_Hate_and_Offensive': 1430, 'Offensive_Language': 1430})


In [15]:
x_ros

tweet
0     "@Blackman38Tide: @WhaleLookyHere @HowdyDowdy1...
1     "@CB_Baby24: @white_thunduh alsarabsss" hes a ...
2     "@DevilGrimz: @VigxRArts you're fucking gay, b...
3     "@MarkRoundtreeJr: LMFAOOOO I HATE BLACK PEOPL...
4     "@NoChillPaz: "At least I'm not a nigger" http...
...                                                 ...
4285                           don't be on that ho shit
4286  Bitches be like "New Avi &gt;&gt;" and I'm jus...
4287  RT @KingHorseDick: Lol RT @youngtravo Nigga li...
4288  This shit is retarded &#8220;@_llVlllVlX: &#12...
4289  RT @reshell_: Keshun be like it aint nothing t...

[4290 rows x 1 columns]

In [16]:
y_ros

0              Hate_Speech
1              Hate_Speech
2              Hate_Speech
3              Hate_Speech
4              Hate_Speech
               ...        
4285    Offensive_Language
4286    Offensive_Language
4287    Offensive_Language
4288    Offensive_Language
4289    Offensive_Language
Name: class, Length: 4290, dtype: object

In [17]:
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [18]:
# remove whitespaces
x_ros['tweet']=x_ros['tweet'].str.strip()

In [19]:
# lowercase the text
x_ros['tweet'] = x_ros['tweet'].str.lower()

In [20]:
#remove punctuation
punc = string.punctuation
table = str.maketrans('','',punc)
x_ros['tweet']=x_ros['tweet'].apply(lambda x: x.translate(table))

In [21]:
# tokenizing each message
x_ros['tweet']=x_ros.apply(lambda x: x['tweet'].split(' '),axis=1)

In [22]:
# removing stopwords
x_ros['tweet'] = x_ros.apply(lambda x: [word for word in x['tweet'] if word not in stopwords.words('english')],axis=1)

In [23]:
# stemming
ps = PorterStemmer()
x_ros['tweet']= x_ros.apply(lambda x: [ps.stem(word) for word in x['tweet']],axis=1)

In [24]:
# remove single letter words
x_ros['tweet'] = x_ros.apply(lambda x: ' '.join([word for word in x['tweet'] if len(word)>1]),axis=1)

In [25]:
x_ros[0:10]

tweet
0  blackman38tid whalelookyher howdydowdy11 queer...
1  cbbaby24 whitethunduh alsarabsss he beaner smh...
2  devilgrimz vigxrart your fuck gay blacklist ho...
3  markroundtreejr lmfaoooo hate black peopl http...
4  nochillpaz least im nigger httptcorgja7cfoit\n...
5  notoriousbm95 whiteponyjr ariza snake coward l...
6  rtnba drake new shoe releas nikejordan ye ther...
7  theomaxximu gerryshalloweenparti httptco3ycrsr...
8  ashlingwild itsnotadam bore suppos cute faggot...
9  bigbootybishopp whitethunduh lassen cc coach w...

In [26]:
y_ros[0:10]

0    Hate_Speech
1    Hate_Speech
2    Hate_Speech
3    Hate_Speech
4    Hate_Speech
5    Hate_Speech
6    Hate_Speech
7    Hate_Speech
8    Hate_Speech
9    Hate_Speech
Name: class, dtype: object

In [27]:
X=n.array(x_ros['tweet'])
y=n.array(y_ros)

In [28]:
X[0:10]

array(['blackman38tid whalelookyher howdydowdy11 queer gaywad',
       'cbbaby24 whitethunduh alsarabsss he beaner smh tell he mexican',
       'devilgrimz vigxrart your fuck gay blacklist hoe hold tehgodclan anyway httptcoxuccwoetmn',
       'markroundtreejr lmfaoooo hate black peopl httpstcornvd2nlcdr there black peopl nigger',
       'nochillpaz least im nigger httptcorgja7cfoit\n\nlmfao',
       'notoriousbm95 whiteponyjr ariza snake coward least isnt crippl like hero roach lmaoo',
       'rtnba drake new shoe releas nikejordan ye there glitter shoe httptcoqctplxhexm dude fag',
       'theomaxximu gerryshalloweenparti httptco3ycrsrnjhc halloween yesterday stupid nigger',
       'ashlingwild itsnotadam bore suppos cute faggot sometim',
       'bigbootybishopp whitethunduh lassen cc coach want feel youll get nig doubt'],
      dtype=object)

In [29]:
y[0:10]

array(['Hate_Speech', 'Hate_Speech', 'Hate_Speech', 'Hate_Speech',
       'Hate_Speech', 'Hate_Speech', 'Hate_Speech', 'Hate_Speech',
       'Hate_Speech', 'Hate_Speech'], dtype=object)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv_X=cv.fit_transform(X) # fit the data

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(cv_X,y,test_size=0.2,random_state=42)

In [32]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [33]:
predict=rfc.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score
print('Accuracy of Random Forest Classifier is ',accuracy_score(y_test,predict)*100)

Accuracy of Random Forest Classifier is  80.41958041958041


In [35]:
from sklearn.metrics import confusion_matrix
print('confusion matrix of Random Forest Classifier\n\n',confusion_matrix(y_test,predict))

confusion matrix of Random Forest Classifier

 [[205  43  65]
 [ 10 274  11]
 [ 24  15 211]]


In [36]:
from sklearn.metrics import classification_report
print('Classification report of Random Forest Classifier\n\n',classification_report(y_test,predict))

Classification report of Random Forest Classifier

                        precision    recall  f1-score   support

          Hate_Speech       0.86      0.65      0.74       313
No_Hate_and_Offensive       0.83      0.93      0.87       295
   Offensive_Language       0.74      0.84      0.79       250

             accuracy                           0.80       858
            macro avg       0.81      0.81      0.80       858
         weighted avg       0.81      0.80      0.80       858

